// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var POSTS = [
  { slug: "wellness-travel-intentional-luxury", title: "Wellness Travel: Intentional Luxury from Puerto Rico", lang: "en/es", topic: "wellness" },
  { slug: "what-luxury-travel-really-means", title: "What Luxury Travel Really Means", lang: "en", topic: "philosophy" },
  { slug: "do-travel-agents-really-help-save-money", title: "Do Travel Agents Really Help Save Money?", lang: "en", topic: "advisor-value" },
  { slug: "micro-vacaciones-futuro-del-viaje", title: "Micro-vacaciones: el futuro del viaje", lang: "es", topic: "trends" },
  { slug: "river-cruising-new-generation", title: "River Cruising: A New Generation", lang: "en", topic: "cruises" },
  { slug: "luna-de-miel-puerto-rico-2026", title: "Luna de miel desde Puerto Rico 2026", lang: "es", topic: "honeymoon" },
  { slug: "cruceros-fluviales-ama-vs-avalon-vs-riverside", title: "Cruceros fluviales: AmaWaterways vs Avalon vs Riverside", lang: "es", topic: "cruises" },
  { slug: "vale-la-pena-asesor-viajes-2026", title: "\xBFVale la pena un asesor de viajes en 2026?", lang: "es", topic: "advisor-value" },
  { slug: "vuelos-puerto-rico-portugal", title: "Vuelos Puerto Rico \u2192 Portugal", lang: "es", topic: "flights" },
  { slug: "maldivas-desde-puerto-rico-guia", title: "Maldivas desde Puerto Rico: gu\xEDa completa", lang: "es", topic: "destinations" },
  { slug: "servicios-concierge-viaje", title: "Servicios de concierge de viaje", lang: "es", topic: "concierge" },
  { slug: "viajes-sin-pasaporte-desde-pr", title: "Viajes sin pasaporte desde Puerto Rico", lang: "es", topic: "destinations" },
  { slug: "luxury-solo-female-travel", title: "Luxury Solo Female Travel", lang: "en", topic: "solo-travel" }
];
var BASE = "https://www.sjuluxetravel.com/blog/";
var list_blog_posts_default = defineTool({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "Return the published SJU Luxe Travel blog posts with title, slug, language, topic, and full URL. Optional topic filter.",
  inputSchema: {
    topic: z.string().optional().describe("Optional topic filter (e.g. wellness, cruises, honeymoon).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ topic }) => {
    const filtered = topic ? POSTS.filter((p) => p.topic === topic.toLowerCase()) : POSTS;
    const rows = filtered.map((p) => ({ ...p, url: BASE + p.slug }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { posts: rows }
    };
  }
});

// src/lib/mcp/tools/list-destinations.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var DESTINATIONS = [
  { slug: "maldives", name: "Maldives", summary: "Overwater villas, private-island wellness, seaplane transfers from Mal\xE9.", url: "https://www.sjuluxetravel.com/destinations/maldives" },
  { slug: "portugal", name: "Portugal", summary: "Lisbon, Douro Valley, Alentejo \u2014 quintas, wine, historic pousadas.", url: "https://www.sjuluxetravel.com/destinations/portugal" },
  { slug: "mexico", name: "Mexico", summary: "Riviera Maya, Yucat\xE1n, Los Cabos \u2014 Chabl\xE9, Rosewood, One&Only.", url: "https://www.sjuluxetravel.com/destinations/mexico" }
];
var list_destinations_default = defineTool2({
  name: "list_destinations",
  title: "List destinations",
  description: "Return SJU Luxe Travel's featured luxury destinations with a short summary and canonical URL.",
  inputSchema: {
    slug: z2.string().optional().describe("Optional single destination slug (maldives | portugal | mexico).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const rows = slug ? DESTINATIONS.filter((d) => d.slug === slug.toLowerCase()) : DESTINATIONS;
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { destinations: rows }
    };
  }
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_contact_info_default = defineTool3({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Return SJU Luxe Travel contact details: advisor, phone, email, location, booking page, and social links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      agency: "SJU Luxe Travel",
      advisor: "Denise Santiago",
      phone: "+1 (617) 935-5714",
      email: "dsantiago@ncmconcierge.com",
      location: "San Juan, Puerto Rico",
      website: "https://www.sjuluxetravel.com",
      contactPage: "https://www.sjuluxetravel.com/contact",
      credentials: ["AV-166 Lic. 237", "Florida ST15578", "California 2090937-50", "Washington 603189022", "Iowa 1202"],
      social: {
        instagram: "https://www.instagram.com/sjuluxetravel/",
        facebook: "https://www.facebook.com/sjuluxetravel",
        linkedin: "https://www.linkedin.com/company/sju-luxe-travel"
      },
      languages: ["English", "Spanish"]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/request-trip-quote.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var request_trip_quote_default = defineTool4({
  name: "request_trip_quote",
  title: "Request trip quote",
  description: "Draft a luxury trip inquiry for SJU Luxe Travel. Returns a formatted inquiry summary and the contact URL the traveler should use to send it. Does not submit anything \u2014 the traveler must reach out via the contact page, email, or phone.",
  inputSchema: {
    traveler_name: z3.string().min(1).describe("Traveler's full name."),
    destination: z3.string().min(1).describe("Requested destination or region."),
    travel_dates: z3.string().min(1).describe("Approximate travel dates or window."),
    party_size: z3.number().int().positive().describe("Number of travelers."),
    budget_usd: z3.number().positive().optional().describe("Total budget in USD (optional)."),
    notes: z3.string().optional().describe("Style, occasion, preferences, or must-haves.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: (input) => {
    const summary = [
      `Trip inquiry for ${input.traveler_name}`,
      `Destination: ${input.destination}`,
      `Dates: ${input.travel_dates}`,
      `Travelers: ${input.party_size}`,
      input.budget_usd ? `Budget: $${input.budget_usd.toLocaleString()} USD` : null,
      input.notes ? `Notes: ${input.notes}` : null
    ].filter(Boolean).join("\n");
    const payload = {
      inquiry: summary,
      next_steps: {
        contactPage: "https://www.sjuluxetravel.com/contact",
        email: "dsantiago@ncmconcierge.com",
        phone: "+1 (617) 935-5714"
      }
    };
    return {
      content: [{ type: "text", text: summary + "\n\nSend to: dsantiago@ncmconcierge.com\nOr visit: https://www.sjuluxetravel.com/contact" }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "sju-luxe-travel-mcp",
  title: "SJU Luxe Travel",
  version: "0.1.0",
  instructions: "Tools for SJU Luxe Travel, a bilingual (EN/ES) luxury travel agency based in San Juan, Puerto Rico. Use `list_blog_posts` and `list_destinations` for content, `get_contact_info` for advisor details, and `request_trip_quote` to draft a personalized trip inquiry the traveler can send to the advisor.",
  tools: [list_blog_posts_default, list_destinations_default, get_contact_info_default, request_trip_quote_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
